### ISSUE TITLE
Shop menu opens when you destroy a machine

### ISSUE THREAD

**Issue by wildweasel486** [wildweasel486/ww-cash2#6]
I whacked a vending machine with the upgraded Crowbar until it blew up, and for some reason, the shop menu opened. I'm unsure why; the Decorate does not call scripts at all.

**Comment by edthebat** [comment]
Ah, I think I might know why... I have the machines set their Special to call that script so that, along with USESPECIAL, they can be activated with the use key. By default, actors call their special when killed. I'll see if I can find a way to have them clear their special when killed so they don't call the script.

**Comment by edthebat** [comment]
Got a fix in place. Now, as far as the engine cares, they never truly 'die', but all effects for the player should be the same (minus the bug).

**Comment by wildweasel486** [comment]
Thanks again, sir!

**Comment by wildweasel486** [comment]
Sorry, I have to reopen this; apparently despite our best efforts, the machines still spontaneously open their menus when telefragged. (Probably the best place to test this is Doom 2 Map03.)

**Comment by edthebat** [comment]
That's a puzzler, especially since they have DamageFactor Telefrag,0. On top of that, they now technically no longer have a Death state at all. I'll look into it...

**Comment by edthebat** [comment]
A development-only flag seems to be the solution to the issue. Pushing now...
