### ISSUE TITLE
More than six items per shop?

### ISSUE THREAD

**Issue by wildweasel486** [wildweasel486/ww-cash2#7]
There's a possibility that I may start adding items to the shops soon; currently, the "scrollbar" on the shop menu is just a static graphic that is placed on the SHOPGRID graphic via Textures, but if I wanted to add more than the six items that can be displayed, is the system capable of displaying that many yet?

**Comment by edthebat** [comment]
Right now, there's no support for a scrolling menu list. I've been brainstorming about ways to insert that, though. I'll give that more focus if the need will arise sooner than later.

**Comment by wildweasel486** [comment]
I suspect "the need" may be arising very soon, as I prepare to add yet more items to the Level 2 and 4 vending machines.

**Comment by edthebat** [comment]
Then I'll look into it tonight (tomorrow at the latest).

**Comment by wildweasel486** [comment]
Cool, no rush though. If it comes to making the scrollbar work, remember to remove it from the Textures entry for SHOPGRID first.

**Comment by wildweasel486** [comment]
Okay, I've taken a look at the code as it stands - this is certainly a start, and I'll see about actually adding more items to the shops as I have them made (see todo-list.txt for some ideas I'd like to bounce off someone). I must report a bug, though: the selection box goes off screen when the menu is scrolled.

(Incidentally: should I brighten up the selection boxes? I think I'll do that. It's a bit hard to see them.)

**Comment by edthebat** [comment]
I've just fixed the bug with the box. I'll be pushing it soon. And this may be just a shortcut to cover for things I think might be a bit beyond me, but I was thinking perhaps the scrollbar could be replaced with just some indicators (I'd use arrows) to show that there's more items if the player keeps going down the list (or up, once they've gone far enough). I'd put them to the left of the menu, next to the product boxes (with a little bit of space in between since I'd still like to put in those checkmarks for owned items that you requested in your original diagram).

It wouldn't hurt to make the cursors brighter, though I would also suggest making everything else except the text darker, to help the words stand out better. Also, perhaps add some subtle translucency so the player can see through the menu while shopping? Since the game doesn't pause when a shop is open (unlike with the Strife dialogue system), situational awareness is critical.

**Comment by wildweasel486** [comment]
I think I agree with most of these; a scrollbar would be a bit difficult to work, now that I think of it, so I'll see about getting some flashing arrows in the graphics resource at some point.

I've already made the cursors brighter a minute ago; I do think I should lower brightness of the other stuff though. As far as transparency goes, well, I'd say situational awareness should be the player's problem; it's up to them to make sure the area's clear before messing with the menu. (Alternate answer: I actually don't know how I'm gonna do that, because I don't remember if we can adjust the alpha of HudMessage, and I certainly can't do it in Textures.)

**Comment by edthebat** [comment]
HudMessage indeed has an alpha option. I can screw with it a little bit to show you how it might look, and if you're not outright disgusted with it, we'll consider implementing it for good. Oh, and speaking of the menu covering up the player's view, I've realized that a lot of messages are being displayed by print(), which is not only way too inflexible, but it gets displayed beneath the shop menu. I'll convert them to HudMessages, and then you can decide how you want to adjust their position and any other aesthetics.

**Comment by wildweasel486** [comment]
That all sounds quite good. As far as converting the shop messages to HudMessage, I might revise SHOPGRID a bit more to add a small message line to the bottom of the window that would also display a controls guide until a message is displayed.
